project.base-dir : file:///C:/Users/SSG/IdeaProjects/LoginSpringBootI18N


spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  thymeleaf:
    cache: false
#    prefix: ${project.base-dir}/src/main/resources/templates/
#  resources:
#    static-locations: ${project.base-dir}/src/main/resources/static/

  data:
    rest:
      default-media-type: application/json

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=LOGIN
    username: adminewf
    password: P@ssw0rd

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

    hibernate:
      ddl-auto: update
      show-sql: false


server:
  servlet:
    context-path: /GUY
  port: 8080
