project.base-dir : file:///C:/Users/SSG/IdeaProjects/LoginSpringBootI18N

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  thymeleaf:
    cache: false
#    prefix: ${project.base-dir}/src/main/resources/templates/
#  resources:
#    static-locations: ${project.base-dir}/src/main/resources/static/

  data:
    rest:
      default-media-type: application/json


server:
  servlet:
    context-path: /GUY
